### ISSUE TITLE
Syntax error on delayed assign with unit

### ISSUE THREAD

**Issue by sonologic** [steveicarus/iverilog#251]
Consider the following code:

```
module foo;

wire a;

assign #1ns a = 1'b1;

endmodule
```

In version 10.1 which I installed with `apt install iverilog` on my ubuntu 18.04 system, this is accepted. However, with a compiled v10_branch version, this results in a syntax error:

```
$ iverilog -o delayed_assign.out delayed_assign.v 
delayed_assign.v:5: syntax error
delayed_assign.v:5: error: syntax error in left side of continuous assignment.
$
```

A `git bisect` points to commit 9449c468655faed73a19bd19e4028d503ff6659b as the first bad commit.

**Comment by sonologic** [comment]
I guess specifying a time unit for a delay is a systemverilog feature? However, it seems the default of whether this is supported or not has changed? I'm not entirely sure this is actually a bug now, just that code that compiles with default options in 10.1 will not compile anymore without specifying non-default language support flags (`-g2005-sv` makes it compile again).

**Comment by sonologic** [comment]
Looked it up in the IEEE standard documents, and indeed time units are specified in 1800-2005, not in 1364-2005. The commit I mentioned fixed some bugs in determining language support, and the current behaviour in v10_branch is correct, the behaviour in 10.1 was incorrect.

Sorry for the noise.
