### PR TITLE
configure.ac: Use C++11 with GNU Extensions

### PR DESCRIPTION
**Pull request by sevan**
It seems the project actually relies on GNU Extensions rather than the C++11 standard alone.
Allows the project to build with GCC 5.5 which has [full C++11 support](https://gcc.gnu.org/projects/cxx-status.html#cxx11).

### CODE REVIEW

**Comment by larsclausen** [comment]
Do you have an example where it fails without gnu extensions?

**Comment by sevan** [comment]
```
g++-5 -std=gnu++11 -DHAVE_CONFIG_H -I. -Ilibmisc -I/Users/sme/Sandbox/tigerbrew/opt/zlib/include -I/Users/sme/Sandbox/tigerbrew/opt/bzip2/include -I/Users/sme/Sandbox/tigerbrew/opt/flex/include -isystem/Users/sme/Sandbox/tigerbrew/include -F/Users/sme/Sandbox/tigerbrew/Frameworks -Wall -Wextra -Wshadow   -Os -w -pipe -mcpu=970 -faltivec -mmacosx-version-min=10.4 -std=c++11 -MD -c main.cc -o main.o
In file included from /Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/exception:162:0,
                 from /Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/ios:39,
                 from /Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/ostream:38,
                 from /Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/iostream:39,
                 from main.cc:41:
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/exception_ptr.h: In member function 'std::__exception_ptr::exception_ptr::operator __vector(4) __bool int() const':
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/exception_ptr.h:139:16: error: cannot convert 'void* const' to '__vector(4) __bool int' in return
       { return _M_exception_object; }
                ^
In file included from /Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/exception:163:0,
                 from /Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/ios:39,
                 from /Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/ostream:38,
                 from /Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/iostream:39,
                 from main.cc:41:
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/nested_exception.h: In member function 'void std::nested_exception::rethrow_nested() const':
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/nested_exception.h:72:11: error: could not convert '((const std::nested_exception*)this)->std::nested_exception::_M_ptr' from 'const std::__exception_ptr::exception_ptr' to 'bool'
       if (_M_ptr)
           ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h: At global scope:
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:98:24: error: expected primary-expression before '__attribute__'
       enum { __value = bool(_Sp::__value) || bool(_Tp::__value) };
                        ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:98:24: error: expected '}' before '__attribute__'
In file included from /Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/stl_algobase.h:61:0,
                 from /Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/char_traits.h:39,
                 from /Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/ios:40,
                 from /Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/ostream:38,
                 from /Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/iostream:39,
                 from main.cc:41:
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:98:41: error: invalid use of qualified-name '_Sp::__value'
       enum { __value = bool(_Sp::__value) || bool(_Tp::__value) };
                                         ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:98:41: error: expected ';' at end of member declaration
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:98:43: error: expected unqualified-id before '||' token
       enum { __value = bool(_Sp::__value) || bool(_Tp::__value) };
                                           ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:99:37: error: '__value' was not declared in this scope
       typedef typename __truth_type<__value>::__type __type;
                                     ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:99:44: error: template argument 1 is invalid
       typedef typename __truth_type<__value>::__type __type;
                                            ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:107:15: error: '__false_type' does not name a type
       typedef __false_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:114:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:122:15: error: '__false_type' does not name a type
       typedef __false_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:129:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:139:15: error: '__false_type' does not name a type
       typedef __false_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:150:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:157:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:164:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:171:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:179:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:188:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:195:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:203:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:210:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:217:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:224:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:231:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:238:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:245:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:252:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:291:15: error: '__false_type' does not name a type
       typedef __false_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:299:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:306:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:313:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:323:15: error: '__false_type' does not name a type
       typedef __false_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:330:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:340:15: error: '__false_type' does not name a type
       typedef __false_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:348:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:356:23: error: expected template-name before '<' token
     : public __traitor<__is_integer<_Tp>, __is_floating<_Tp> >
                       ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:356:23: error: expected '{' before '<' token
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:356:23: error: expected unqualified-id before '<' token
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:364:23: error: expected template-name before '<' token
     : public __traitor<__is_arithmetic<_Tp>, __is_pointer<_Tp> >
                       ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:364:23: error: expected '{' before '<' token
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:364:23: error: expected unqualified-id before '<' token
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:374:15: error: '__false_type' does not name a type
       typedef __false_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:381:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:389:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:397:15: error: '__false_type' does not name a type
       typedef __false_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:404:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:411:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:418:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:428:15: error: '__false_type' does not name a type
       typedef __false_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:439:15: error: '__true_type' does not name a type
       typedef __true_type __type;
               ^
/Users/sme/Sandbox/tigerbrew/Cellar/gcc5/5.5.0/include/c++/5.5.0/bits/cpp_type_traits.h:444:1: error: expected declaration before '}' token
 } // namespace
 ^
make: *** [main.o] Error 1
```

**Comment by larsclausen** [comment]
That's interesting, the errors are all in the standard library that comes with the compiler. I would have expected it to use some pragmas or something to enable the extensions. I'm not opposed to using `gnu++11` to workaround this. But maybe there is a better way, lets see what others say.

**Comment by sevan** [comment]
Hmm, might actually be worth bringing in [ax_cxx_compile_stdcxx](https://www.gnu.org/software/autoconf-archive/ax_cxx_compile_stdcxx.html) from the autoconf-archive rather than nailing the standard up (happy to do the autoconf bits if needed).

**Comment by caryr** [comment]
Are there issues if the `-std=gnu++11` is removed?

I'm confused because you are saying we are using GNU extensions, but things fail to compile when you enable the gnu extension. I semi regularly compile Icarus on a variety of older machines and it has always compiled without issue.

I'll build some of them now to make sure everything is okay.

**Comment by caryr** [comment]
I just check on Ubuntu 16.04 which uses gcc-5.4 and clang-3.8. Both compiled the latest iverilog with no issues using -std=c++11.

I see no reason gcc-5.5 would have issues if gcc-5.4 works.

**Comment by caryr** [comment]
Icarus also compiled cleanly on Ubuntu 18.04 which uses gcc-7.5 and clang-6.0. Can you double check that nothing is misconfigured on your end.

**Comment by caryr** [comment]
I believe we are using a specific C++ version so that people do not accidentally add newer construct that would break compilation on older machines. This is needed since most of our development is done using more modern OS versions.

**Comment by martinwhitaker** [comment]
I wondered if it was the two contradictory `-std=` on the command line that was causing the problem, but looking at the last CI run on MacOS, it has the same. But maybe it's a bug in GCC 5.5 specifically.

The CI runs on Linux only have the single `-std=c11`. @caryr, was that also true for your test with GCC 5.4?

**Comment by caryr** [comment]
Yes, only a single `-std=` line.

**Comment by sevan** [comment]
Apologies, issue is not exclusive to GCC 5.5, reproduced on GCC 7.5, however the issue is at my end.
You cannot turn on optimisation and build to strict standards using GCC. The framework I was using was turning on optimisation.
For the sake of completeness, you should be able to reproduce the issue if you configure with `CFLAGS=-Os` or we can skip it & just close the issue. :)

**Comment by caryr** [comment]
I do not use `-Os`, but everything I build uses `-O2` except debug/valgrind builds that use `-O0`.

What framework are you using? Is it possible it is misconfigured or has a bug? I believe we all just use configure options and then straight `make`.

**Comment by sevan** [comment]
Looks like it is specific to the powerpc target. Tried forcing "-Os -mcpu=foo" on macos with GCC 13.2 & Ubuntu 23.10 riscv64 with GCC 13.2 without issue.
There's nothing misconfigured. Tigerbrew just defaults to "-Os -mcpu=bar -altivec" which trips up GCC 5.5 & 7.5.

**Comment by caryr** [comment]
It seems like this is not a bug in Icarus but something in the environment. If you try overriding the optimization to be -O0 or -O2 does that give a clean compile? I will explicitly try -Os to make sure it's not that specific optimization flag when I have some time.

If `-Os -mcpu=bar -altivec` is valid and you are getting errors in the system headers then that implies the compiler or something in the environment has a problem/inconsistency. If there were any issues in Icarus I would expect an Icarus file to be in there somewhere other than the base that is calling the header file.

Have you asked someone who is familiar with Tigerbrew?

**Comment by sevan** [comment]
You are correct, nothing to do with Icarus. I meant I've only been able to hit the issue on the powerpc system and not on other combinations in the previous reply. Just got to remember to mark the Icarus formula to build without optimisation and all should be ok.
